/**
 * GENERATED by scripts/render-vcluster-manifests.mjs — do not edit.
 *
 * Rendered from the vcluster chart v0.36.1 (k8s distro, emptyDir, OSS
 * image, telemetry off) with --kube-version 1.35.7, plus the
 * driver-authored D19 NetworkPolicies. The vc-config Secret is deliberately
 * absent: the driver regenerates it per instance from VCLUSTER_CONFIG_YAML
 * because its content embeds the namespace (extraSANs, exportKubeConfig).
 *
 * The instance name is fixed ('vc'): service `vc`, kubeconfig secret
 * `vc-vc`, config secret `vc-config-vc`. The namespace is the
 * per-instance identity — every `__VC_NS__` token below is replaced by the
 * driver at apply time.
 */

export const VCLUSTER_CHART_VERSION = '0.36.1';
export const VCLUSTER_NAME = 'vc';
export const VCLUSTER_NS_TOKEN = '__VC_NS__';
export const VCLUSTER_RUNTIME_CLASS_TOKEN = '__VC_RUNTIME_CLASS__';

/**
 * Substitute the RuntimeClass token, or DELETE the line carrying it.
 *
 * A tier with no RuntimeClass is not a tier with an empty one: the apiserver
 * validates `runtimeClassName` as an RFC 1123 subdomain, so substituting `''`
 * renders `runtimeClassName: ""` and every claim on the container tier dies at
 * apply with `Deployment "vc" is invalid`. The field is optional — absence is
 * the only spelling for "the node default" — so the line goes rather than its
 * value. Measured on nanoco-k8s-runc, 2026-08-27: the Kata tier (which always
 * names a class) never reached this, so the substitution read as correct.
 */
export function applyVclusterRuntimeClass(yaml: string, runtimeClassName: string): string {
  if (runtimeClassName) return yaml.replaceAll(VCLUSTER_RUNTIME_CLASS_TOKEN, runtimeClassName);
  return yaml
    .split('\n')
    .filter((line) => !line.includes(VCLUSTER_RUNTIME_CLASS_TOKEN))
    .join('\n');
}
export const VCLUSTER_PARENT_CLUSTER_ROLE = 'nanoclaw-dev-env-vcluster';
/** Kubeconfig secret the syncer writes at runtime (never rendered by helm). */
export const VCLUSTER_KUBECONFIG_SECRET = 'vc-vc';
export const VCLUSTER_CONFIG_SECRET = 'vc-config-vc';
/** Every image an instance needs; the pool node must have them pre-supplied. */
export const VCLUSTER_IMAGES = [
  'ghcr.io/loft-sh/kubernetes:v1.36.0',
  'ghcr.io/loft-sh/vcluster-oss:0.36.1',
  'docker.io/coredns/coredns:1.14.2',
  'mirror.gcr.io/library/alpine:3.20',
] as const;

export const VCLUSTER_MANIFESTS = `
# Source: vcluster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-vc
  namespace: __VC_NS__
  labels:
    app: vcluster
    chart: "vcluster-0.36.1"
    release: "vc"
    heritage: "Helm"
---
# Source: vcluster/templates/workload-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-workload-vc
  namespace: __VC_NS__
  labels:
    app: vcluster
    chart: "vcluster-0.36.1"
    release: "vc"
    heritage: "Helm"
---
# Source: vcluster/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vc-vc
  namespace: __VC_NS__
  labels:
    app: vcluster
    chart: "vcluster-0.36.1"
    release: "vc"
    heritage: "Helm"
subjects:
  - kind: ServiceAccount
    name: vc-vc
    namespace: __VC_NS__
roleRef:
  kind: ClusterRole
  name: nanoclaw-dev-env-vcluster
  apiGroup: rbac.authorization.k8s.io
---
# Source: vcluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vc
  namespace: __VC_NS__
  labels:
    app: vcluster
    chart: "vcluster-0.36.1"
    release: "vc"
    heritage: "Helm"
    vcluster.loft.sh/service: "true"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 0
      protocol: TCP
    - name: kubelet
      port: 10250
      targetPort: 8443
      nodePort: 0
      protocol: TCP
  selector:
    app: vcluster
    release: "vc"
---
# Source: vcluster/templates/statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc
  namespace: __VC_NS__
  labels:
    app: vcluster
    chart: "vcluster-0.36.1"
    release: "vc"
    heritage: "Helm"
spec:
  selector:
    matchLabels:
      app: vcluster
      release: "vc"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      annotations:
        vClusterConfigHash: "97b0b51e3d0076a06b3513b8f0a724196ea6912534ad97c5280840234e0a0c11"
      labels:
        app: vcluster
        release: "vc"
    spec:
      terminationGracePeriodSeconds: 15
      serviceAccountName: vc-vc
      runtimeClassName: "__VC_RUNTIME_CLASS__"
      volumes:        
        - name: helm-cache
          emptyDir: {}
        - emptyDir: {}
          name: binaries
        - name: tmp
          emptyDir: {}
        - name: certs
          emptyDir: {}
        - name: vcluster-config
          secret:
            secretName: vc-config-vc
        - name: data
          emptyDir: {}
      initContainers:
        
        - name: kubernetes
          image: "ghcr.io/loft-sh/kubernetes:v1.36.0"
          volumeMounts:
            - mountPath: /binaries
              name: binaries
          command:
            - cp
          args:
            - -r 
            - /kubernetes/.
            - /binaries/
          securityContext:
            {}
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 40m
              memory: 64Mi
      enableServiceLinks: true
      containers:
        - name: syncer
          image: "ghcr.io/loft-sh/vcluster-oss:0.36.1"
          imagePullPolicy: 
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8443
              scheme: HTTPS
            periodSeconds: 2
            timeoutSeconds: 3
            failureThreshold: 60
          startupProbe:
            httpGet:
              path: /readyz
              port: 8443
              scheme: HTTPS
            periodSeconds: 6
            timeoutSeconds: 3
            failureThreshold: 300
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 0
            runAsUser: 0
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 8Gi
              memory: 2Gi
            requests:
              cpu: 100m
              ephemeral-storage: 400Mi
              memory: 512Mi
          env:
            - name: VCLUSTER_NAME
              value: "vc"
            - name: LOFT_LOG_ENCODING
              value: console
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:            
            - name: data
              mountPath: /data
            - name: binaries
              mountPath: /binaries
            - name: certs
              mountPath: /pki
            - name: helm-cache
              mountPath: /.cache/helm
            - name: vcluster-config
              mountPath: /var/lib/vcluster
            - name: tmp
              mountPath: /tmp
---
# driver-authored (not from chart): D19 egress seal
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dev-env-default-deny
  namespace: __VC_NS__
spec:
  # Ordinary tenant workloads retain same-namespace communication. Governed
  # control-plane workloads opt out with this label and receive explicit
  # parent-authored flows before a claimed environment is handed out.
  podSelector:
    matchExpressions:
      - key: nanoco.dev/trust-boundary
        operator: DoesNotExist
      - key: k8s-app
        operator: NotIn
        values: [vcluster-kube-dns]
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - podSelector: {}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
  ingress:
    - from:
        - podSelector: {}
---
# Governed-child trusted workload isolation. Other stamps carry none of these
# labels, so these policies are inert for them. They exist before a warm child
# is claimed; no open window precedes the parent edge/relay materialization.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: governed-control-default-deny
  namespace: __VC_NS__
spec:
  podSelector:
    matchLabels: {nanoco.dev/trust-boundary: control}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: governed-gateway, namespace: __VC_NS__}
spec:
  podSelector:
    matchLabels: {app: gateway, nanoco.dev/trust-boundary: control}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - {key: nanoco.dev/trust-boundary, operator: DoesNotExist}
        - podSelector: {matchLabels: {app: nanoclaw-host}}
      ports:
        - {protocol: TCP, port: 9443}
        - {protocol: TCP, port: 9444}
        - {protocol: TCP, port: 9446}
  egress:
    - to: [{podSelector: {matchLabels: {k8s-app: vcluster-kube-dns}}}]
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}, {protocol: UDP, port: 1053}, {protocol: TCP, port: 1053}]
    - to: [{podSelector: {matchLabels: {app: governance}}}]
      ports: [{protocol: TCP, port: 10260}]
    - to: [{podSelector: {matchLabels: {app: postgresql}}}]
      ports: [{protocol: TCP, port: 5432}]
    - to: [{podSelector: {matchLabels: {app: backlot}}}]
      ports:
        - {protocol: TCP, port: 9080}
        - {protocol: TCP, port: 9081}
        - {protocol: TCP, port: 9082}
        - {protocol: TCP, port: 9083}
        - {protocol: TCP, port: 9084}
        - {protocol: TCP, port: 9085}
    - to: [{podSelector: {matchLabels: {app.kubernetes.io/name: parent-egress-relay}}}]
      ports: [{protocol: TCP, port: 15001}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: governed-governance, namespace: __VC_NS__}
spec:
  podSelector:
    matchLabels: {app: governance, nanoco.dev/trust-boundary: control}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{podSelector: {matchLabels: {app: gateway}}}]
      ports: [{protocol: TCP, port: 10260}]
    - from: [{podSelector: {matchLabels: {app: governed-child-edge}}}]
      ports: [{protocol: TCP, port: 10255}]
  egress:
    - to: [{podSelector: {matchLabels: {k8s-app: vcluster-kube-dns}}}]
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}, {protocol: UDP, port: 1053}, {protocol: TCP, port: 1053}]
    - to: [{podSelector: {matchLabels: {app: nanoclaw-host}}}]
      ports: [{protocol: TCP, port: 10262}]
    - to: [{podSelector: {matchLabels: {app: postgresql}}}]
      ports: [{protocol: TCP, port: 5432}]
    - to: [{podSelector: {matchLabels: {app: backlot}}}]
      ports:
        - {protocol: TCP, port: 9080}
        - {protocol: TCP, port: 9081}
        - {protocol: TCP, port: 9082}
        - {protocol: TCP, port: 9083}
        - {protocol: TCP, port: 9084}
        - {protocol: TCP, port: 9085}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: governed-host, namespace: __VC_NS__}
spec:
  podSelector:
    matchLabels: {app: nanoclaw-host, nanoco.dev/trust-boundary: control}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: [{podSelector: {matchLabels: {app: governance}}}]
      ports: [{protocol: TCP, port: 10262}]
  egress:
    - to: [{podSelector: {matchLabels: {k8s-app: vcluster-kube-dns}}}]
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}, {protocol: UDP, port: 1053}, {protocol: TCP, port: 1053}]
    - to: [{podSelector: {matchLabels: {app: gateway}}}]
      ports: [{protocol: TCP, port: 9443}, {protocol: TCP, port: 9444}, {protocol: TCP, port: 9446}]
    - to: [{podSelector: {matchLabels: {app: postgresql}}}]
      ports: [{protocol: TCP, port: 5432}]
    - to: [{podSelector: {matchLabels: {app: backlot}}}]
      ports:
        - {protocol: TCP, port: 9080}
        - {protocol: TCP, port: 9081}
        - {protocol: TCP, port: 9082}
        - {protocol: TCP, port: 9083}
        - {protocol: TCP, port: 9084}
        - {protocol: TCP, port: 9085}
    - to: [{podSelector: {matchLabels: {app.kubernetes.io/name: parent-egress-relay}}}]
      ports: [{protocol: TCP, port: 15001}]
    - to: [{podSelector: {matchLabels: {app: vcluster}}}]
      ports: [{protocol: TCP, port: 443}, {protocol: TCP, port: 8443}]
    # The workspace controller lives in the companion namespace, so this is the
    # one egress the Host needs that leaves __VC_NS__. Its own ingress policy
    # already names app: nanoclaw-host in this namespace; without the matching
    # rule here only one half of the pair allows the call, and every ensure()
    # fails as fetch failed at workspace-plane's request() while the
    # controller's log stays empty because the request never arrives.
    - to:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: __VC_NS__-workspace}}
          podSelector: {matchLabels: {app.kubernetes.io/name: nanoclaw-workspace-controller}}
      ports: [{protocol: TCP, port: 8787}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: governed-postgresql, namespace: __VC_NS__}
spec:
  podSelector:
    matchLabels: {app: postgresql, nanoco.dev/trust-boundary: control}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {matchLabels: {app: gateway}}
        - podSelector: {matchLabels: {app: governance}}
        - podSelector: {matchLabels: {app: nanoclaw-host}}
      ports: [{protocol: TCP, port: 5432}]
  # The PKI mint runs as PostgreSQL's first init container. It has an
  # explicitly projected, narrow ServiceAccount token; the long-running
  # database container does not. NetworkPolicy is pod-scoped, so permit only
  # this pod to reach only its own vcluster API. Authentication still refuses
  # the database container, which has no token or client credential.
  egress:
    - to: [{podSelector: {matchLabels: {app: vcluster}}}]
      ports: [{protocol: TCP, port: 443}, {protocol: TCP, port: 8443}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: {name: governed-backlot, namespace: __VC_NS__}
spec:
  podSelector:
    matchLabels: {app: backlot, nanoco.dev/trust-boundary: control}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {matchLabels: {app: gateway}}
        - podSelector: {matchLabels: {app: governance}}
        - podSelector: {matchLabels: {app: nanoclaw-host}}
        - podSelector: {matchLabels: {app: governed-child-edge}}
      ports:
        - {protocol: TCP, port: 9080}
        - {protocol: TCP, port: 9081}
        - {protocol: TCP, port: 9082}
        - {protocol: TCP, port: 9083}
        - {protocol: TCP, port: 9084}
        - {protocol: TCP, port: 9085}
  egress:
    - to: [{podSelector: {matchLabels: {k8s-app: vcluster-kube-dns}}}]
      ports: [{protocol: UDP, port: 53}, {protocol: TCP, port: 53}, {protocol: UDP, port: 1053}, {protocol: TCP, port: 1053}]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dev-env-control-plane
  namespace: __VC_NS__
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - vcluster
      - key: vcluster.loft.sh/managed-by
        operator: DoesNotExist
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 169.254.169.254/32
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
`;

export const VCLUSTER_CONFIG_YAML = `controlPlane:
  advanced:
    cloudControllerManager:
      enabled: true
    defaultImageRegistry: ""
    globalMetadata:
      annotations: {}
    headlessService:
      annotations: {}
      labels: {}
    konnectivity:
      agent:
        enabled: true
        extraArgs: []
        extraEnv: []
        image: ""
        imagePullPolicy: ""
        nodeSelector: {}
        replicas: 1
        tolerations: []
      server:
        enabled: true
        extraArgs: []
    kubeVip:
      enabled: false
    podDisruptionBudget:
      enabled: false
    registry:
      anonymousPull: true
      config: {}
      enabled: false
    serviceAccount:
      annotations: {}
      enabled: true
      imagePullSecrets: []
      labels: {}
      name: ""
    virtualScheduler:
      enabled: false
    workloadServiceAccount:
      annotations: {}
      enabled: true
      imagePullSecrets: []
      labels: {}
      name: ""
  backingStore:
    database:
      embedded:
        enabled: false
        extraArgs: []
      external:
        caFile: ""
        certFile: ""
        connector: ""
        dataSource: ""
        enabled: false
        extraArgs: []
        identityProvider: ""
        keyFile: ""
    etcd:
      deploy:
        enabled: false
        headlessService:
          annotations: {}
        service:
          annotations: {}
          enabled: true
        statefulSet:
          annotations: {}
          enableServiceLinks: true
          enabled: true
          env: []
          extraArgs: []
          highAvailability:
            replicas: 1
          image:
            registry: registry.k8s.io
            repository: etcd
            tag: 3.6.8-0
          imagePullPolicy: ""
          labels: {}
          persistence:
            addVolumeMounts: []
            addVolumes: []
            volumeClaim:
              accessModes:
              - ReadWriteOnce
              enabled: true
              retentionPolicy: Retain
              size: 5Gi
              storageClass: ""
            volumeClaimTemplates: []
          pods:
            annotations: {}
            labels: {}
          resources:
            requests:
              cpu: 20m
              memory: 150Mi
          scheduling:
            affinity: {}
            nodeSelector: {}
            podManagementPolicy: Parallel
            priorityClassName: ""
            tolerations: []
            topologySpreadConstraints: []
          security:
            containerSecurityContext: {}
            podSecurityContext: {}
      embedded:
        enabled: false
        extraArgs: []
        migrateFromDeployedEtcd: false
      external:
        enabled: false
        endpoint: ""
        tls:
          caFile: ""
          certFile: ""
          keyFile: ""
  coredns:
    deployment:
      affinity: {}
      annotations: {}
      image: ""
      labels: {}
      nodeSelector: {}
      pods:
        annotations: {}
        labels: {}
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 170Mi
        requests:
          cpu: 20m
          memory: 64Mi
      tolerations: []
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            k8s-app: vcluster-kube-dns
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
    embedded: false
    enabled: true
    overwriteConfig: ""
    overwriteManifests: ""
    priorityClassName: ""
    security:
      containerSecurityContext: {}
      podSecurityContext: {}
    service:
      annotations: {}
      labels: {}
      spec:
        type: ClusterIP
  distro:
    k8s:
      apiServer:
        command: []
        enabled: true
        extraArgs: []
      controllerManager:
        command: []
        enabled: true
        extraArgs: []
      enabled: false
      env: []
      image:
        registry: ghcr.io
        repository: loft-sh/kubernetes
        tag: v1.36.0
      imagePullPolicy: ""
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
      scheduler:
        command: []
        enabled: false
        extraArgs: []
      securityContext: {}
      version: ""
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: false
    host: my-host.com
    labels: {}
    pathType: ImplementationSpecific
    spec:
      tls: []
  proxy:
    bindAddress: 0.0.0.0
    extraSANs:
    - vc.__VC_NS__.svc
    - vc.__VC_NS__.svc.cluster.local
    port: 8443
  service:
    annotations: {}
    enabled: true
    httpsNodePort: 0
    kubeletNodePort: 0
    labels: {}
    spec:
      type: ClusterIP
  serviceMonitor:
    annotations: {}
    enabled: false
    labels: {}
  standalone:
    dataDir: /var/lib/vcluster
    joinNode:
      containerd:
        enabled: true
      enabled: true
  statefulSet:
    annotations: {}
    args: []
    command: []
    enableServiceLinks: true
    env: []
    highAvailability:
      leaseDuration: 60
      renewDeadline: 40
      replicas: 1
      retryPeriod: 15
    hostAliases: []
    image:
      registry: ghcr.io
      repository: loft-sh/vcluster-oss
      tag: ""
    imagePullPolicy: ""
    initContainers: []
    labels: {}
    persistence:
      addVolumeMounts: []
      addVolumes: []
      binariesVolume:
      - emptyDir: {}
        name: binaries
      dataVolume: []
      volumeClaim:
        accessModes:
        - ReadWriteOnce
        enabled: false
        retentionPolicy: Retain
        size: 5Gi
        storageClass: ""
      volumeClaimTemplates: []
    pods:
      annotations: {}
      labels: {}
    probes:
      livenessProbe:
        enabled: true
        failureThreshold: 60
        initialDelaySeconds: 60
        periodSeconds: 2
        timeoutSeconds: 3
      readinessProbe:
        enabled: true
        failureThreshold: 60
        periodSeconds: 2
        timeoutSeconds: 3
      startupProbe:
        enabled: true
        failureThreshold: 300
        periodSeconds: 6
        timeoutSeconds: 3
    resources:
      limits:
        cpu: "1"
        ephemeral-storage: 8Gi
        memory: 2Gi
      requests:
        cpu: 100m
        ephemeral-storage: 400Mi
        memory: 512Mi
    scheduling:
      affinity: {}
      nodeSelector: {}
      podManagementPolicy: Parallel
      priorityClassName: ""
      tolerations: []
      topologySpreadConstraints: []
    security:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsGroup: 0
        runAsUser: 0
      podSecurityContext: {}
    sidecarContainers: []
    workingDir: ""
  tlsRoute:
    annotations: {}
    apiVersion: gateway.networking.k8s.io/v1
    enabled: false
    host: my-host.com
    labels: {}
    parentRefs: []
    spec: {}
deploy:
  cni:
    flannel:
      enabled: true
  ingressNginx:
    defaultIngressClass: true
    enabled: false
  kubeProxy:
    config: {}
    enabled: true
    extraArgs: []
    extraEnv: []
    image: ""
    imagePullPolicy: ""
    nodeSelector: {}
    tolerations: []
  localPathProvisioner:
    enabled: true
  metallb:
    enabled: false
    ipAddressPool:
      addresses: []
      l2Advertisement: true
  metricsServer:
    enabled: false
experimental:
  deploy:
    host:
      manifests: ""
      manifestsTemplate: ""
    vcluster:
      helm: []
      manifests: ""
      manifestsTemplate: ""
  docker:
    loadBalancer:
      enabled: true
      forwardPorts: true
    registryProxy:
      enabled: true
  nodeMonitors: []
  proxy:
    customResources: {}
  syncSettings:
    setOwner: true
exportKubeConfig:
  additionalSecrets: []
  context: ""
  insecure: false
  secret:
    name: ""
    namespace: ""
  server: https://vc.__VC_NS__.svc:443
  serviceAccount:
    clusterRole: ""
    name: ""
    namespace: ""
integrations:
  certManager:
    enabled: false
    sync:
      fromHost:
        clusterIssuers:
          enabled: true
          selector:
            labels: {}
      toHost:
        certificates:
          enabled: true
        issuers:
          enabled: true
  externalSecrets:
    enabled: false
    sync:
      fromHost:
        clusterStores:
          enabled: false
          selector:
            matchLabels: {}
      toHost:
        externalSecrets:
          selector:
            matchLabels: {}
        stores:
          enabled: false
          selector:
            matchLabels: {}
    webhook:
      enabled: false
  istio:
    enabled: false
    sync:
      toHost:
        destinationRules:
          enabled: true
        gateways:
          enabled: true
        virtualServices:
          enabled: true
  kubeVirt:
    enabled: false
    sync:
      dataVolumes:
        enabled: false
      virtualMachineClones:
        enabled: true
      virtualMachineInstanceMigrations:
        enabled: true
      virtualMachineInstances:
        enabled: true
      virtualMachinePools:
        enabled: true
      virtualMachines:
        enabled: true
    webhook:
      enabled: true
  metricsServer:
    enabled: false
    nodes: true
    pods: true
logging:
  encoding: console
networking:
  advanced:
    clusterDomain: cluster.local
    fallbackHostCluster: false
    proxyKubelets:
      byHostname: true
      byIP: true
  podCIDR: 10.244.0.0/16
  replicateServices:
    fromHost: []
    toHost: []
  resolveDNS: []
plugins: {}
policies:
  centralAdmission:
    mutatingWebhooks: []
    validatingWebhooks: []
  limitRange:
    annotations: {}
    default:
      cpu: "1"
      ephemeral-storage: 8Gi
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      ephemeral-storage: 3Gi
      memory: 128Mi
    enabled: auto
    labels: {}
    max: {}
    min: {}
  networkPolicy:
    annotations: {}
    controlPlane:
      egress: []
      ingress: []
    enabled: false
    fallbackDns: 8.8.8.8
    labels: {}
    workload:
      egress: []
      ingress: []
      publicEgress:
        cidr: 0.0.0.0/0
        enabled: true
        except:
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 10.0.0.0/8
        - 169.254.0.0/16
        - 172.16.0.0/12
        - 192.168.0.0/16
  resourceQuota:
    annotations: {}
    enabled: auto
    labels: {}
    quota:
      count/configmaps: 100
      count/endpoints: 40
      count/persistentvolumeclaims: 20
      count/pods: 20
      count/secrets: 100
      count/services: 20
      limits.cpu: 20
      limits.ephemeral-storage: 160Gi
      limits.memory: 40Gi
      requests.cpu: 10
      requests.ephemeral-storage: 60Gi
      requests.memory: 20Gi
      requests.storage: 100Gi
      services.loadbalancers: 1
      services.nodeports: 0
    scopeSelector:
      matchExpressions: []
    scopes: []
privateNodes:
  autoNodes: []
  autoUpgrade:
    concurrency: 1
    containerSecurityContext: {}
    enabled: true
    podSecurityContext: {}
  daemon:
    controlPlaneLoadBalancer:
      enabled: false
      kubeProxy: true
      port: 11343
    enabled: false
  enabled: false
  joinNode:
    containerd:
      enabled: true
  kubelet:
    config: {}
  vpn:
    enabled: false
    nodeToNode:
      enabled: false
rbac:
  clusterRole:
    enabled: auto
    extraRules: []
    overwriteRules: []
  role:
    enabled: true
    extraRules: []
    overwriteRules: []
sync:
  fromHost:
    configMaps:
      enabled: false
      mappings:
        byName: {}
    csiDrivers:
      enabled: auto
    csiNodes:
      enabled: auto
    csiStorageCapacities:
      enabled: auto
    deviceClasses:
      enabled: false
    events:
      enabled: true
    gatewayClasses:
      enabled: false
    gateways:
      allowedRoutes:
        defaultVirtualNamespacePolicy: {}
        overrides: []
      enabled: false
      mappings:
        byName: {}
      metadata:
        exposeSourceGateway: false
      sanitize:
        certificateRefs: true
        infrastructure: true
      selector: {}
      status:
        exposeAddresses: false
    ingressClasses:
      enabled: false
    nodes:
      clearImageStatus: false
      enabled: false
      selector:
        all: false
        labels: {}
      syncBackChanges: false
    priorityClasses:
      enabled: false
    runtimeClasses:
      enabled: false
    secrets:
      enabled: false
      mappings:
        byName: {}
    storageClasses:
      enabled: auto
  toHost:
    configMaps:
      all: false
      enabled: true
    endpointSlices:
      enabled: true
    endpoints:
      enabled: true
    gatewayApi:
      backendTLSPolicies:
        enabled: false
      enabled: false
      gateways:
        enabled: false
      httpRoutes:
        enabled: false
      referenceGrants:
        enabled: auto
      tlsRoutes:
        enabled: false
    ingresses:
      enabled: false
    namespaces:
      enabled: false
      mappingsOnly: false
    networkPolicies:
      enabled: false
    persistentVolumeClaims:
      enabled: true
    persistentVolumes:
      enabled: false
    podDisruptionBudgets:
      enabled: false
    pods:
      enabled: true
      enforceTolerations: []
      hybridScheduling:
        enabled: false
        hostSchedulers: []
      priorityClassName: ""
      rewriteHosts:
        enabled: true
        initContainer:
          image:
            registry: mirror.gcr.io
            repository: library/alpine
            tag: "3.20"
          resources:
            limits:
              cpu: 30m
              memory: 64Mi
            requests:
              cpu: 30m
              memory: 64Mi
      runtimeClassName: "__VC_RUNTIME_CLASS__"
      translateImage: {}
      useSecretsForSATokens: false
    priorityClasses:
      enabled: false
    resourceClaimTemplates:
      enabled: false
    resourceClaims:
      enabled: false
    secrets:
      all: false
      enabled: true
    serviceAccounts:
      enabled: false
    services:
      enabled: true
    storageClasses:
      enabled: false
telemetry:
  enabled: false`;
