-- Generated by scripts/pg-baseline-from-sqlite.ts. Do not edit by hand.

-- Covers the frozen SQLite-only migration set; portable migrations run afterward.



CREATE TABLE "agent_destinations" (
  agent_group_id text NOT NULL,
  local_name text NOT NULL,
  target_type text NOT NULL,
  target_id text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (agent_group_id, local_name)
);

CREATE TABLE "agent_group_members" (
  user_id text NOT NULL,
  agent_group_id text NOT NULL,
  added_by text,
  added_at text NOT NULL,
  PRIMARY KEY (user_id, agent_group_id)
);

CREATE TABLE "agent_groups" (
  id text PRIMARY KEY,
  name text NOT NULL,
  folder text NOT NULL UNIQUE,
  agent_provider text,
  created_at text NOT NULL
);

CREATE TABLE "agent_message_policies" (
  from_agent_group_id text NOT NULL,
  to_agent_group_id text NOT NULL,
  approver text NOT NULL,
  created_at text NOT NULL,
  PRIMARY KEY (from_agent_group_id, to_agent_group_id)
);

CREATE TABLE "chat_sdk_kv" (
  key text PRIMARY KEY,
  value text NOT NULL,
  expires_at bigint
);

CREATE TABLE "chat_sdk_lists" (
  key text NOT NULL,
  idx bigint NOT NULL,
  value text NOT NULL,
  expires_at bigint,
  PRIMARY KEY (key, idx)
);

CREATE TABLE "chat_sdk_locks" (
  thread_id text PRIMARY KEY,
  token text NOT NULL,
  expires_at bigint NOT NULL
);

CREATE TABLE "chat_sdk_subscriptions" (
  thread_id text PRIMARY KEY,
  subscribed_at text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

CREATE TABLE "container_configs" (
  agent_group_id text PRIMARY KEY,
  provider text,
  model text,
  effort text,
  image_tag text,
  assistant_name text,
  max_messages_per_prompt bigint,
  skills text NOT NULL DEFAULT '"all"',
  mcp_servers text NOT NULL DEFAULT '{}',
  packages_apt text NOT NULL DEFAULT '[]',
  packages_npm text NOT NULL DEFAULT '[]',
  additional_mounts text NOT NULL DEFAULT '[]',
  updated_at text NOT NULL,
  cli_scope text NOT NULL DEFAULT 'group',
  timezone text
);

CREATE TABLE "messaging_group_agents" (
  id text PRIMARY KEY,
  messaging_group_id text NOT NULL,
  agent_group_id text NOT NULL,
  session_mode text DEFAULT 'shared',
  priority bigint DEFAULT 0,
  created_at text NOT NULL,
  engage_mode text,
  engage_pattern text,
  sender_scope text,
  ignored_message_policy text,
  threads bigint,
  UNIQUE(messaging_group_id, agent_group_id)
);

CREATE TABLE "messaging_groups" (
  id text PRIMARY KEY,
  channel_type text NOT NULL,
  platform_id text NOT NULL,
  instance text NOT NULL,
  name text,
  is_group bigint DEFAULT 0,
  unknown_sender_policy text NOT NULL DEFAULT 'strict',
  created_at text NOT NULL,
  denied_at text,
  UNIQUE(channel_type, platform_id, instance)
);

CREATE TABLE "pending_approvals" (
  approval_id text PRIMARY KEY,
  session_id text,
  request_id text NOT NULL,
  action text NOT NULL,
  payload text NOT NULL,
  created_at text NOT NULL,
  agent_group_id text,
  channel_type text,
  platform_id text,
  platform_message_id text,
  expires_at text,
  status text NOT NULL DEFAULT 'pending',
  title text NOT NULL DEFAULT '',
  options_json text NOT NULL DEFAULT '[]',
  approver_user_id text,
  question text NOT NULL DEFAULT ''
);

CREATE TABLE "pending_channel_approvals" (
  messaging_group_id text PRIMARY KEY,
  agent_group_id text NOT NULL,
  original_message text NOT NULL,
  approver_user_id text NOT NULL,
  created_at text NOT NULL,
  title text NOT NULL DEFAULT '',
  options_json text NOT NULL DEFAULT '[]',
  question text NOT NULL DEFAULT ''
);

CREATE TABLE "pending_questions" (
  question_id text PRIMARY KEY,
  session_id text NOT NULL,
  message_out_id text NOT NULL,
  platform_id text,
  channel_type text,
  thread_id text,
  title text NOT NULL,
  options_json text NOT NULL,
  created_at text NOT NULL
);

CREATE TABLE "pending_sender_approvals" (
  id text PRIMARY KEY,
  messaging_group_id text NOT NULL,
  agent_group_id text NOT NULL,
  sender_identity text NOT NULL,
  sender_name text,
  original_message text NOT NULL,
  approver_user_id text NOT NULL,
  created_at text NOT NULL,
  title text NOT NULL DEFAULT '',
  options_json text NOT NULL DEFAULT '[]',
  question text NOT NULL DEFAULT '',
  UNIQUE(messaging_group_id, sender_identity)
);

CREATE TABLE "schema_version" (
  version bigint PRIMARY KEY,
  name text NOT NULL,
  applied text NOT NULL
);

CREATE TABLE "sessions" (
  id text PRIMARY KEY,
  agent_group_id text NOT NULL,
  messaging_group_id text,
  thread_id text,
  agent_provider text,
  status text DEFAULT 'active',
  container_status text DEFAULT 'stopped',
  last_active text,
  created_at text NOT NULL
);

CREATE TABLE "unregistered_senders" (
  channel_type text NOT NULL,
  platform_id text NOT NULL,
  user_id text,
  sender_name text,
  reason text NOT NULL,
  messaging_group_id text,
  agent_group_id text,
  message_count bigint NOT NULL DEFAULT 1,
  first_seen text NOT NULL,
  last_seen text NOT NULL,
  PRIMARY KEY (channel_type, platform_id)
);

CREATE TABLE "user_dms" (
  user_id text NOT NULL,
  channel_type text NOT NULL,
  messaging_group_id text NOT NULL,
  resolved_at text NOT NULL,
  PRIMARY KEY (user_id, channel_type)
);

CREATE TABLE "user_roles" (
  user_id text NOT NULL,
  role text NOT NULL,
  agent_group_id text,
  granted_by text,
  granted_at text NOT NULL
);

CREATE TABLE "users" (
  id text PRIMARY KEY,
  kind text NOT NULL,
  display_name text,
  created_at text NOT NULL
);



ALTER TABLE "agent_destinations" ADD CONSTRAINT "fk_agent_destinations_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "agent_group_members" ADD CONSTRAINT "fk_agent_group_members_added_by" FOREIGN KEY ("added_by") REFERENCES "users" ("id");

ALTER TABLE "agent_group_members" ADD CONSTRAINT "fk_agent_group_members_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "agent_group_members" ADD CONSTRAINT "fk_agent_group_members_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "agent_message_policies" ADD CONSTRAINT "fk_agent_message_policies_from_agent_group_id" FOREIGN KEY ("from_agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "agent_message_policies" ADD CONSTRAINT "fk_agent_message_policies_to_agent_group_id" FOREIGN KEY ("to_agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "container_configs" ADD CONSTRAINT "fk_container_configs_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id") ON DELETE CASCADE;

ALTER TABLE "messaging_group_agents" ADD CONSTRAINT "fk_messaging_group_agents_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "messaging_group_agents" ADD CONSTRAINT "fk_messaging_group_agents_messaging_group_id" FOREIGN KEY ("messaging_group_id") REFERENCES "messaging_groups" ("id");

ALTER TABLE "pending_approvals" ADD CONSTRAINT "fk_pending_approvals_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "pending_approvals" ADD CONSTRAINT "fk_pending_approvals_session_id" FOREIGN KEY ("session_id") REFERENCES "sessions" ("id");

ALTER TABLE "pending_channel_approvals" ADD CONSTRAINT "fk_pending_channel_approvals_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "pending_channel_approvals" ADD CONSTRAINT "fk_pending_channel_approvals_messaging_group_id" FOREIGN KEY ("messaging_group_id") REFERENCES "messaging_groups" ("id");

ALTER TABLE "pending_questions" ADD CONSTRAINT "fk_pending_questions_session_id" FOREIGN KEY ("session_id") REFERENCES "sessions" ("id");

ALTER TABLE "pending_sender_approvals" ADD CONSTRAINT "fk_pending_sender_approvals_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "pending_sender_approvals" ADD CONSTRAINT "fk_pending_sender_approvals_messaging_group_id" FOREIGN KEY ("messaging_group_id") REFERENCES "messaging_groups" ("id");

ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_messaging_group_id" FOREIGN KEY ("messaging_group_id") REFERENCES "messaging_groups" ("id");

ALTER TABLE "user_dms" ADD CONSTRAINT "fk_user_dms_messaging_group_id" FOREIGN KEY ("messaging_group_id") REFERENCES "messaging_groups" ("id");

ALTER TABLE "user_dms" ADD CONSTRAINT "fk_user_dms_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_agent_group_id" FOREIGN KEY ("agent_group_id") REFERENCES "agent_groups" ("id");

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_granted_by" FOREIGN KEY ("granted_by") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD CONSTRAINT "fk_user_roles_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id");



CREATE INDEX IF NOT EXISTS idx_agent_dest_target ON agent_destinations(target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_chat_sdk_kv_expires_at ON chat_sdk_kv(expires_at);

CREATE INDEX IF NOT EXISTS idx_chat_sdk_lists_expires_at ON chat_sdk_lists(expires_at);

CREATE INDEX IF NOT EXISTS idx_chat_sdk_locks_expires_at ON chat_sdk_locks(expires_at);

CREATE INDEX IF NOT EXISTS idx_pending_approvals_action_status ON pending_approvals(action, status);

CREATE INDEX IF NOT EXISTS idx_pending_sender_approvals_mg ON pending_sender_approvals(messaging_group_id);

CREATE INDEX IF NOT EXISTS idx_sessions_agent_group ON sessions(agent_group_id);

CREATE INDEX IF NOT EXISTS idx_sessions_lookup ON sessions(messaging_group_id, thread_id);

CREATE INDEX IF NOT EXISTS idx_unregistered_senders_last_seen ON unregistered_senders(last_seen);

CREATE INDEX IF NOT EXISTS idx_user_roles_scope ON user_roles(agent_group_id, role);

CREATE UNIQUE INDEX IF NOT EXISTS idx_schema_version_name ON schema_version(name);



INSERT INTO schema_version (version, name, applied) VALUES

  (1, 'initial-v2-schema', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (2, 'chat-sdk-state', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (3, 'pending-approvals', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (4, 'agent-destinations', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (5, 'agent-message-policies', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (6, 'pending-approvals-title-options', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (7, 'approvals-approver-user-id', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (8, 'dropped-messages', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (9, 'drop-pending-credentials', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (10, 'engage-modes', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (11, 'pending-sender-approvals', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (12, 'channel-registration', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (13, 'approval-render-metadata', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (14, 'container-configs', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (15, 'cli-scope', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (16, 'messaging-group-instance', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (17, 'wiring-threads-override', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (18, 'container-config-timezone', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
  (19, 'approval-question-render-metadata', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))

ON CONFLICT (name) DO NOTHING;
